### ISSUE TITLE
镜像在仓库有更新，但是onekey返回not need update

### ISSUE THREAD

**Issue by whkwkxsyf1991** [onlyLTY/oneKeyUpdate#15]
大佬您好，我使用了绿联的分支遇到如下的几个问题，
第一：使用全局代理后，还是有部分镜像信息查询失败
![image](https://github.com/onlyLTY/oneKeyUpdate/assets/131899817/914c96b5-8a40-4856-a026-03b8ec7683dc)
第二：镜像信息查询成功的，返回的数据是not need update，但是实际仓库里面我看了下是有更新版本的。
![image](https://github.com/onlyLTY/oneKeyUpdate/assets/131899817/79b9ea97-ff0f-4770-b5f8-be0f1a110dfc)
![image](https://github.com/onlyLTY/oneKeyUpdate/assets/131899817/da253ec8-1c92-4096-9052-9d253eb2b5a4)
![image](https://github.com/onlyLTY/oneKeyUpdate/assets/131899817/f6361612-900a-4917-ab16-dfed37cb1d78)
望能解惑呀
另外就是能不能搞个容器自定义代理的支持呀，全局代理没法一直开着，哭

**Comment by onlyLTY** [comment]
第一个没法获取的原因是镜像的tag是none了，应该是以前拉过，然后后面又拉了同名镜像，这样tag就会被顶掉，可以不用管，第二个的话我查查看。自定义代理的话后面可以做上

**Comment by onlyLTY** [comment]
最新版本已修复。现在应该不再需要代理了
