### ISSUE TITLE
请问极空间用户如何正确安装oneKeyUpdate？

### ISSUE THREAD

**Issue by liangliang-wh** [onlyLTY/oneKeyUpdate#17]
我使用的是极空间Z2S 4G，是ARM架构，请问极空间用户如何正确安装oneKeyUpdate？

**Comment by onlyLTY** [comment]
拉取 0nlylty/one-key-update:zspace镜像
创建容器，需要host模式，环境内填写极空间的账号，nas的ip
访问ip:12712

readme有说明

**Comment by liangliang-wh** [comment]
谢谢，可以用了，非常感谢：）


------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月24日(星期二) 晚上11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [onlyLTY/oneKeyUpdate] 请问极空间用户如何正确安装oneKeyUpdate？ (Issue #17)





 
拉取 0nlylty/one-key-update:zspace镜像
 创建容器，需要host模式，环境内填写极空间的账号，nas的ip
 访问ip:12712
 
readme有说明
