### ISSUE TITLE
拉取镜像失败

### ISSUE THREAD

**Issue by Homoe-hs** [onlyLTY/oneKeyUpdate#19]
我使用的是绿联，按照给出的文档通过ssh成功安装后，出现了这个问题
![image](https://github.com/onlyLTY/dockerCopilot/assets/62646930/44688971-3cad-4210-8f66-92511e752b2b)
然后马上登陆就被退出

**Comment by onlyLTY** [comment]
我排查一下

**Comment by onlyLTY** [comment]
在最新版本应该修复了。可以按照https://blog.lty.wiki/index.php/archives/58/部署下
