### ISSUE TITLE
更新之后还是提示更新

### ISSUE THREAD

**Issue by zhao-wuyan** [onlyLTY/oneKeyUpdate#20]
我是绿联用户，我用onekey更新了容器之后，页面还是提示有更新。容器我看了已经是最新的了，这个检测逻辑是根据什么来的。

**Comment by onlyLTY** [comment]
可能是因为缓存导致的，以前考虑到docker hub连接性问题所以用的是国内镜像站。目前版本是build time来确定。后续会改为digest id来进行判断。同时已经找到方法解决了连接性问题，所以后续版本会把数据源改回docker hub

**Comment by kokojacket** [comment]
期待，大佬加油，催更催更~

**Comment by onlyLTY** [comment]
最近版本已经实现
