### ISSUE TITLE
onekey自身更新问题

### ISSUE THREAD

**Issue by LONER-LAU** [onlyLTY/oneKeyUpdate#21]
v1.0.7-zspac一直提示有更新，点击后提示“” 更新程序失败 {"status":"","msg":"need"}“”

**Comment by onlyLTY** [comment]
可以暂时无视他，已知bug，后面修复

**Comment by nageshuizeii** [comment]
![CleanShot 2024-01-30 at 23 34 05@2x](https://github.com/onlyLTY/dockerCopilot/assets/16527235/879e1bda-7cd1-48bf-a9b2-da2d3785a71f)
v1.0.3-UGREEN无法升级到2.0

**Comment by onlyLTY** [comment]
由于项目更名还有就是变化较大的原因，无法做到直接升级。可以参考教程重新部署一下https://blog.lty.wiki/index.php/archives/58/
