### ISSUE TITLE
2.0版会造成绿联的docker服务自动关闭（2.0.4版本已尝试修复，麻烦各位帮忙观察下）

### ISSUE THREAD

**Issue by WYithal** [onlyLTY/oneKeyUpdate#22]

**Comment by onlyLTY** [comment]
已收到相关反馈。我查询了ugos系统日志以及dc的容器日志，感觉可能是dc触发了ugos系统的bug导致了引擎关闭。具体原因还在查询。如果可以的话请使用ssh创建的方式尝试创建，然后帮忙观察下是否会出现docker服务被关闭的情况。
`docker run -d --privileged -p 12712:12712 -e secretKey=自己设置密码，需要大于八位且非纯数字 -e DOCKER_HOST=unix:///var/run/docker.sock -e hubURL=https://docker.nju.edu.cn -v /var/run/docker.sock:/var/run/docker.sock -v 自己设置路径。目前存储备份文件，未来可能存储配置文件:/data --restart=always --name dockerCopilot 0nlylty/dockercopilot:UGREEN`

**Comment by WYithal** [comment]
> 已收到相关反馈。我查询了ugos系统日志以及dc的容器日志，感觉可能是dc触发了ugos系统的bug导致了引擎关闭。具体原因还在查询。如果可以的话请使用ssh创建的方式尝试创建，然后帮忙观察下是否会出现docker服务被关闭的情况。 `docker run -d --privileged -p 12712:12712 -e secretKey=自己设置密码，需要大于八位且非纯数字 -e DOCKER_HOST=unix:///var/run/docker.sock -e hubURL=https://docker.nju.edu.cn -v /var/run/docker.sock:/var/run/docker.sock -v 自己设置路径。目前存储备份文件，未来可能存储配置文件:/data --restart=always --name dockerCopilot 0nlylty/dockercopilot:UGREEN`

好的，回去试下，谢谢

**Comment by WYithal** [comment]
> 已收到相关反馈。我查询了ugos系统日志以及dc的容器日志，感觉可能是dc触发了ugos系统的bug导致了引擎关闭。具体原因还在查询。如果可以的话请使用ssh创建的方式尝试创建，然后帮忙观察下是否会出现docker服务被关闭的情况。 `docker run -d --privileged -p 12712:12712 -e secretKey=自己设置密码，需要大于八位且非纯数字 -e DOCKER_HOST=unix:///var/run/docker.sock -e hubURL=https://docker.nju.edu.cn -v /var/run/docker.sock:/var/run/docker.sock -v 自己设置路径。目前存储备份文件，未来可能存储配置文件:/data --restart=always --name dockerCopilot 0nlylty/dockercopilot:UGREEN`

SSH安装后运行了7小时多，一切正常
![123](https://github.com/onlyLTY/dockerCopilot/assets/13925273/d6926ce5-5e2b-47fd-a109-43b8edc45428)

**Comment by onlyLTY** [comment]
还请持续观察下。我这里的反馈有些是一两天会出现崩溃的情况

**Comment by WYithal** [comment]
> 还请持续观察下。我这里的反馈有些是一两天会出现崩溃的情况

运行2天多了，一切正常，用的是2.0.0版，没有在容器内更到2.0.1
![Picture_2024-02-04_18-13-53](https://github.com/onlyLTY/dockerCopilot/assets/13925273/ed560171-db8f-4817-bd22-b94b141c4b82)

**Comment by onlyLTY** [comment]
感谢。我再查查看

> > 还请持续观察下。我这里的反馈有些是一两天会出现崩溃的情况
> 
> 运行2天多了，一切正常，用的是2.0.0版，没有在容器内更到2.0.1 ![Picture_2024-02-04_18-13-53](https://private-user-images.githubusercontent.com/13925273/302094977-ed560171-db8f-4817-bd22-b94b141c4b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjQ4ODIsIm5iZiI6MTcwNzEyNDU4MiwicGF0aCI6Ii8xMzkyNTI3My8zMDIwOTQ5NzctZWQ1NjAxNzEtZGI4Zi00ODE3LWJkMjItYjk0YjE0MWM0YjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA5MTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZGQ4MWE1YzVmY2JlODRmODQ5NTZhMTdjMjE0Y2Y5YjI4MTE5YzJmY2FjYTM4MGM3NTEyMjBiYmNjNzc3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MB5sPXQ9K7UBLQ6orIUOxKL-Bv8P5wblu5vF4xzpvH4)

**Comment by JeffreyZeng-dev** [comment]
目前使用docker管理器创建的2.0.3版本，依然会导致docker服务停止。

**Comment by onlyLTY** [comment]
> 目前使用docker管理器创建的2.0.3版本，依然会导致docker服务停止。

用ssh创建吧。感觉是触发了绿联的bug。

**Comment by WYithal** [comment]
又发现个问题，今天进后台各种操作都很卡，发现这个系统进程CPU占用基本100%，但是把dockerCopilot停止，瞬间就降下来了
![Picture_2024-03-06_18-47-02](https://github.com/onlyLTY/dockerCopilot/assets/13925273/aac74ef7-43fc-4fd2-933e-6b677f2d8dde)

**Comment by JeffreyZeng-dev** [comment]
> 又发现个问题，今天进后台各种操作都很卡，发现这个系统进程CPU占用基本100%，但是把dockerCopilot停止，瞬间就降下来了 ![Picture_2024-03-06_18-47-02](https://private-user-images.githubusercontent.com/13925273/310484991-aac74ef7-43fc-4fd2-933e-6b677f2d8dde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjkzODYsIm5iZiI6MTcwOTcyOTA4NiwicGF0aCI6Ii8xMzkyNTI3My8zMTA0ODQ5OTEtYWFjNzRlZjctNDNmYy00ZmQyLTkzM2UtNmI2NzdmMmQ4ZGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMGU0YzdlYmYyODA5M2ExN2RkMGQ1YmIxYjYyNDg4Y2EyZmU0OWQ3YzNhZmRhMzAzMmJiYWI0YWFlZDY3ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nfRWD81GmhuIV3HBGGrGy7xbfJRRmhjeZlFbPZAKYMM)

我也遇到了

**Comment by kokojacket** [comment]
@onlyLTY 感觉我出现了类似问题，最近部署了这个之后（威联通），今天所有docker项目均打不开，但是工作正常。portainer显示链接不上，container station也显示不出任何容器。ssh页面使用docker相关命令均无响应。
![image](https://github.com/onlyLTY/dockerCopilot/assets/74887370/7bd17424-c96e-4b40-819d-f51d2e4dbaff)
![image](https://github.com/onlyLTY/dockerCopilot/assets/74887370/7de9d7b7-993a-4dd8-bfcb-5eba6b2a27b2)
![image](https://github.com/onlyLTY/dockerCopilot/assets/74887370/d2b0862f-c361-4e5f-895b-0b048580b8b5)
![image](https://github.com/onlyLTY/dockerCopilot/assets/74887370/c3b0aaec-d43a-4292-8d70-039dc26557b7)

**Comment by onlyLTY** [comment]
感谢各位反馈。我去尝试修复一下

**Comment by onlyLTY** [comment]
204版本尝试修复了下。麻烦各位帮忙看看还会不会出问题

**Comment by JeffreyZeng-dev** [comment]
> 204版本尝试修复了下。麻烦各位帮忙看看还会不会出问题

已更新，目前很稳定，CPU利用率和内存利用率都没有出现什么异常。

**Comment by onlyLTY** [comment]
请问各位在2.0.4版本是否还有遇到docker引擎出现异常的情况

**Comment by kokojacket** [comment]
暂时没有，大佬你搞个交流群吧。想进去摸鱼

**Comment by onlyLTY** [comment]
> 暂时没有，大佬你搞个交流群吧。想进去摸鱼

后面会创建个QQ频道。创建了以后我会在Readme发出来

**Comment by JeffreyZeng-dev** [comment]
我也暂时没有遇到问题，请问这个镜像支持在群晖NAS中部署吗

**Comment by WYithal** [comment]
2.0.4应该是正常了，之前内存占用会慢慢变高，现在不会了
![Picture_2024-03-22_10-06-56](https://github.com/onlyLTY/dockerCopilot/assets/13925273/ebd9b933-5800-4e4e-9808-c50e27d58d3d)

**Comment by onlyLTY** [comment]
> 我也暂时没有遇到问题，请问这个镜像支持在群晖NAS中部署吗

可以，使用ssh方式部署就行

**Comment by JeffreyZeng-dev** [comment]
> > 我也暂时没有遇到问题，请问这个镜像支持在群晖NAS中部署吗
> 
> 可以，使用ssh方式部署就行

-d --privileged -p 12712:12712 -e secretKey=自己设置密码，需要大于八位且非纯数字 -e DOCKER_HOST=unix:///var/run/docker.sock -e hubURL=https://docker.nju.edu.cn -v /var/run/docker.sock:/var/run/docker.sock -v 自己设置路径。目前存储备份文件，未来可能存储配置文件:/data --restart=always --name dockerCopilot 0nlylty/dockercopilot:UGREEN
也是使用这个命令是吧

**Comment by onlyLTY** [comment]
> > > 我也暂时没有遇到问题，请问这个镜像支持在群晖NAS中部署吗
> > 
> > 
> > 可以，使用ssh方式部署就行
> 
> -d --privileged -p 12712:12712 -e secretKey=自己设置密码，需要大于八位且非纯数字 -e DOCKER_HOST=unix:///var/run/docker.sock -e hubURL=https://docker.nju.edu.cn -v /var/run/docker.sock:/var/run/docker.sock -v 自己设置路径。目前存储备份文件，未来可能存储配置文件:/data --restart=always --name dockerCopilot 0nlylty/dockercopilot:UGREEN 也是使用这个命令是吧

对的。最前面需要docker run

**Comment by onlyLTY** [comment]
> > > 我也暂时没有遇到问题，请问这个镜像支持在群晖NAS中部署吗
> > 
> > 
> > 可以，使用ssh方式部署就行
> 
> -d --privileged -p 12712:12712 -e secretKey=自己设置密码，需要大于八位且非纯数字 -e DOCKER_HOST=unix:///var/run/docker.sock -e hubURL=https://docker.nju.edu.cn -v /var/run/docker.sock:/var/run/docker.sock -v 自己设置路径。目前存储备份文件，未来可能存储配置文件:/data --restart=always --name dockerCopilot 0nlylty/dockercopilot:UGREEN 也是使用这个命令是吧

这部分可以删除，用不到了

**Comment by kokojacket** [comment]
今天好像遇到了

**Comment by onlyLTY** [comment]
> 今天好像遇到了

204版本吗？

**Comment by kokojacket** [comment]
> > 今天好像遇到了
> 
> 204版本吗？

是的，后面我关闭后，可以打开portainer，然后重启了一下dockercopilot。到今天又还算正常

**Comment by onlyLTY** [comment]
> > > 今天好像遇到了
> > 
> > 
> > 204版本吗？
> 
> 是的，后面我关闭后，可以打开portainer，然后重启了一下dockercopilot。到今天又还算正常

行，麻烦观察下，如果再次出现的话麻烦联系我
