### ISSUE TITLE
新版本不支持保留旧容器了吗

### ISSUE THREAD

**Issue by hutao521** [onlyLTY/oneKeyUpdate#24]
用的绿联版本是2.0.1。更新容器后发现不会像onekey那样保留老版容器了，感觉保留旧版容器挺好用的，有时候一些镜像升级后没法用还能返回旧版使用。

**Comment by onlyLTY** [comment]
对的。如果需要的话我可以加一个环境变量来控制是否保存。因为每次询问的话有些用户反馈过于麻烦

**Comment by hutao521** [comment]
这个功能挺需要的，希望大佬可以添加个变量来选择是否保存

**Comment by onlyLTY** [comment]
那我下个版本加入吧

**Comment by onlyLTY** [comment]
在2.0.2版本可以通过在环境设置DelOldContainer=false来实现保留旧容器
