### ISSUE TITLE
 error  获取token失败或者无需获取token，继续尝试检查Get "https://index.docker.io/v2/": dial tcp 54.227.20.253:443: i/o timeout        caller=module/checkupdate.go:45

### ISSUE THREAD

**Issue by jiezaizone** [onlyLTY/oneKeyUpdate#25]
部署后运行日志提示  error  获取token失败或者无需获取token，继续尝试检查Get "https://index.docker.io/v2/": dial tcp 54.227.20.253:443: i/o timeout        caller=module/checkupdate.go:45
<img width="1180" alt="image" src="https://github.com/onlyLTY/dockerCopilot/assets/28976666/3eee934b-c591-4a4e-8867-82d0d4acecf1">
请问一下这是怎么回事，哪里部署的不对么？

**Comment by onlyLTY** [comment]
安装没有问题。像是网络请求超时了。请访问下这个页面"https://index.docker.io/"以及"https://registry-1.docker.io"。然后麻烦告知一下打开情况

**Comment by jiezaizone** [comment]
> 安装没有问题。像是网络请求超时了。请访问下这个页面"[https://index.docker.io/"以及"https://registry-1.docker.io"。然后麻烦告知一下打开情况](https://index.docker.io/%22%E4%BB%A5%E5%8F%8A%22https://registry-1.docker.io%22%E3%80%82%E7%84%B6%E5%90%8E%E9%BA%BB%E7%83%A6%E5%91%8A%E7%9F%A5%E4%B8%80%E4%B8%8B%E6%89%93%E5%BC%80%E6%83%85%E5%86%B5)

<img width="502" alt="image" src="https://github.com/onlyLTY/dockerCopilot/assets/28976666/86d3d0c1-37ba-49b3-923f-b3b5f43f7abb">
<img width="437" alt="image" src="https://github.com/onlyLTY/dockerCopilot/assets/28976666/8ad895c5-7690-4b0d-a40a-b0e870996b03">
访问https://registry-1.docker.io/ 提示404

**Comment by onlyLTY** [comment]
那可能是那时候网络连接波动了一下。可以不管他。

**Comment by onlyLTY** [comment]
看图片的话打开都是正常的

**Comment by jiezaizone** [comment]
> 那可能是那时候网络连接波动了一下。可以不管他。
ping了一下https://index.docker.io/v2/ IPv4ping不通，网页之所以能够访问，是连的IPv6.

**Comment by onlyLTY** [comment]
用这个检测。`curl https://index.docker.io/v2/`这个网址ping的检测结果不准确而
