### ISSUE TITLE
保留旧镜像的环境变量，麻烦大佬提供一下

### ISSUE THREAD

**Issue by gulaohu** [onlyLTY/oneKeyUpdate#27]
请问大佬，新版本中更新不会保留老的docker镜像了，我记得哪个评论中有提高过解决办法，环境中添加相关变量，麻烦能把具体变量内容提供一下吗？感谢！

**Comment by Heroleaves** [comment]
在2.0.2版本可以通过在环境设置DelOldContainer=false来实现保留旧容器
