### ISSUE TITLE
使用反向代理后打开网页报404 page not found

### ISSUE THREAD

**Issue by MaksimXue** [onlyLTY/oneKeyUpdate#30]
之前一直用的onekey1.0.3绿联版本，使用Lucky设置反向代理之后网页是可以正常在外网打开的，这次想试试新的copilot，因为所需端口和之前的onekey一致，我就把onekey从docker删除了，拉取配置copilot之后设置了新的反向代理，但是在外网打开网页后直接显示404 page not found，我又上内网试了试，发现在内网是可以使用的，这是什么原因?
![VeryCapture_20240312151605](https://github.com/onlyLTY/dockerCopilot/assets/108639874/6fc94d7d-1000-496a-9af9-1f20e40ac5d4)

**Comment by onlyLTY** [comment]
把12712后面的/containerManager删除即可

**Comment by MaksimXue** [comment]
> 把12712后面的/containerManager删除即可

![VeryCapture_20240314082805](https://github.com/onlyLTY/dockerCopilot/assets/108639874/1f545bc8-c426-4ee2-a42d-222bdbb3e3ae)
![VeryCapture_20240314083124](https://github.com/onlyLTY/dockerCopilot/assets/108639874/9dc375fd-e672-4f1b-996a-7c84cc05c379)
不行，我之前就试过，我的外网访问地址后边每次都会自动加上/containersManager，删掉也会自动跳转到带/containersManager的页面然后显示404

**Comment by onlyLTY** [comment]
> > 把12712后面的/containerManager删除即可
> 
> ![VeryCapture_20240314082805](https://private-user-images.githubusercontent.com/108639874/312658171-1f545bc8-c426-4ee2-a42d-222bdbb3e3ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODE2NDYsIm5iZiI6MTcxMDM4MTM0NiwicGF0aCI6Ii8xMDg2Mzk4NzQvMzEyNjU4MTcxLTFmNTQ1YmM4LWM0MjYtNGVlMi1hNDJkLTIyMmJkYmIzZTNhZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwMTU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWJmYTU0OWQwNDNlNmEzNDZlMmYyZTMwYjVlNGIwNjk3YTM3MWJhYzE2YWRjZmRmNDExMzAyOTRkNDk0YjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eZF09EQiTJkdY-Dpv6rj0vtwVPe1O9b3uLVXkRQPbgg) ![VeryCapture_20240314083124](https://private-user-images.githubusercontent.com/108639874/312658464-9dc375fd-e672-4f1b-996a-7c84cc05c379.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODE2NDYsIm5iZiI6MTcxMDM4MTM0NiwicGF0aCI6Ii8xMDg2Mzk4NzQvMzEyNjU4NDY0LTlkYzM3NWZkLWU2NzItNGYxYi05OTZhLTdjODRjYzA1YzM3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwMTU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzhkMDhkYWVlNzdmNTkwY2U1NjhhMTZiMjVkYjhjOGNhNGNjMTFhZjdjZGNlZmJjN2U3MjhmNzhhNmEyYTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LPXaMry6EmsRcEOwp7EQpcJgum3kfuaVNQQYpVCm2J0) 不行，我之前就试过，我的外网访问地址后边每次都会自动加上/containersManager，删掉也会自动跳转到带/containersManager的页面然后显示404

![image](https://github.com/onlyLTY/dockerCopilot/assets/46625336/108b6f68-7c42-4231-8913-0a39c5bc3ea0)
网址左边有这个图标。点击这个然后清除网站数据试试。这个是浏览器缓存了旧url导致的

**Comment by MaksimXue** [comment]
> > > 把12712后面的/containerManager删除即可
> > 
> > 
> > ![VeryCapture_20240314082805](https://private-user-images.githubusercontent.com/108639874/312658171-1f545bc8-c426-4ee2-a42d-222bdbb3e3ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODE2NDYsIm5iZiI6MTcxMDM4MTM0NiwicGF0aCI6Ii8xMDg2Mzk4NzQvMzEyNjU4MTcxLTFmNTQ1YmM4LWM0MjYtNGVlMi1hNDJkLTIyMmJkYmIzZTNhZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwMTU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWJmYTU0OWQwNDNlNmEzNDZlMmYyZTMwYjVlNGIwNjk3YTM3MWJhYzE2YWRjZmRmNDExMzAyOTRkNDk0YjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eZF09EQiTJkdY-Dpv6rj0vtwVPe1O9b3uLVXkRQPbgg) ![VeryCapture_20240314083124](https://private-user-images.githubusercontent.com/108639874/312658464-9dc375fd-e672-4f1b-996a-7c84cc05c379.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODE2NDYsIm5iZiI6MTcxMDM4MTM0NiwicGF0aCI6Ii8xMDg2Mzk4NzQvMzEyNjU4NDY0LTlkYzM3NWZkLWU2NzItNGYxYi05OTZhLTdjODRjYzA1YzM3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwMTU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzhkMDhkYWVlNzdmNTkwY2U1NjhhMTZiMjVkYjhjOGNhNGNjMTFhZjdjZGNlZmJjN2U3MjhmNzhhNmEyYTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LPXaMry6EmsRcEOwp7EQpcJgum3kfuaVNQQYpVCm2J0) 不行，我之前就试过，我的外网访问地址后边每次都会自动加上/containersManager，删掉也会自动跳转到带/containersManager的页面然后显示404
> 
> ![image](https://private-user-images.githubusercontent.com/46625336/312670462-108b6f68-7c42-4231-8913-0a39c5bc3ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODI0NTUsIm5iZiI6MTcxMDM4MjE1NSwicGF0aCI6Ii80NjYyNTMzNi8zMTI2NzA0NjItMTA4YjZmNjgtN2M0Mi00MjMxLTg5MTMtMGEzOWM1YmMzZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyMDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMTJhZDg2YzliZTA2ODE4Njc2OGYzOTVlNThlZTExYzU4NDRlZWQyYjk0ZTcyNTRkNWJmYTAxY2Y3Yzk1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxOE9bFOZrlUMVWedN5cHlhYc3U8ncGjuEeEgBxqM5k) 网址左边有这个图标。点击这个然后清除网站数据试试。这个是浏览器缓存了旧url导致的

果然是因为浏览器缓存的原因，清除缓存后已经可以正常打开了，非常感谢
