### ISSUE TITLE
建议增加镜像备份功能

### ISSUE THREAD

**Issue by moyun-tian** [onlyLTY/oneKeyUpdate#32]
众所周知的原因部分镜像更新后旧版本可能会存在丢失的风险，建议增加镜像的自定义备份，未来可以通过备份镜像重新安装

**Comment by onlyLTY** [comment]
那备份会比较大，这种可以接受吗？

**Comment by moyun-tian** [comment]
个人完全可以接受，备份本来就是个人数据的一种冗余机制

**Comment by onlyLTY** [comment]
> 个人完全可以接受，备份本来就是个人数据的一种冗余机制

行，那后面做上
