### ISSUE TITLE
一直报错，不知道为什么

### ISSUE THREAD

**Issue by yesuhegaoliao** [onlyLTY/oneKeyUpdate#34]
2024/3/27 22:39:22  	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x5e8
2024/3/27 22:39:22  main.main()
2024/3/27 22:39:22  goroutine 1 [running]:
2024/3/27 22:39:22  
2024/3/27 22:39:22  panic: 请求错误，状态码:422

**Comment by yesugao** [comment]
搞好了，账号填错了，填成了admin，没认真看

**Comment by solisvivi** [comment]
请安排更新极空间。膜拜，感谢！

**Comment by onlyLTY** [comment]
> 请安排更新极空间。膜拜，感谢！

极空间有的啊。看极空间论坛

**Comment by yesugao** [comment]
> 请安排更新极空间。膜拜，感谢！

我的就是极空间，正常使用呀，就是账号给填错了，填成了admin
