### ISSUE TITLE
极空间一直报错

### ISSUE THREAD

**Issue by LONER-LAU** [onlyLTY/oneKeyUpdate#36]
2024/4/1 22:31:33  2024-04-01T22:31:33.733+08:00	 info 	程序版本v2.0.3-zspace	caller=zspace/dockercopilot.go:98
2024/4/1 22:31:33  Starting server at 0.0.0.0:12712...
2024/4/1 22:31:33  2024-04-01T22:31:33.614+08:00	 info 	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024/4/1 22:23:06  2024-04-01T22:23:06.322+08:00	 error 	获取digest失败registry responded to head request with "404 Not Found", auth: "not present"	caller=module/checkupdate.go:54
2024/4/1 22:23:04  2024-04-01T22:23:04.841+08:00	 error 	获取token失败或者无需获取token，继续尝试检查unsupported challenge type from registry	caller=module/checkupdate.go:45

**Comment by onlyLTY** [comment]
account填极空间的管理员账号。用host模式

**Comment by LONER-LAU** [comment]
填写的就是管理员账号，和ONKEY一模一样的，ONKEY可以用，dockerCopilot就不行

**Comment by LONER-LAU** [comment]
我找到原因了，账号密码都是对的，是链接地址总是跳转到OKkey的地址http://IP:12712/containersmanager，而不是http://IP:12712/manager#/containers，清理浏览器就好了
