### ISSUE TITLE
希望能够设置代理服务器

### ISSUE THREAD

**Issue by twilight1015** [onlyLTY/oneKeyUpdate#38]
直接拉取镜像有时候会很慢，希望能够提供自行设置HTTP代理的选项，以便通过clash来加速

**Comment by onlyLTY** [comment]
拉取镜像慢的话需要对docker引擎设置加速。在dc内设置的加速是无法让拉取镜像加速的。dc内能做的是通过加速源拉取镜像。这个目前是已经支持了的
