### ISSUE TITLE
个别容器一直是待更新状态

### ISSUE THREAD

**Issue by leonedit** [onlyLTY/oneKeyUpdate#41]
其实这个问题从OneKey开始就一直有了，登陆以后发现有的容器待更新，结果更新以后仍然显示可以更新

**Comment by onlyLTY** [comment]
这个我联系过出现相同情况的排查。有几种情况，仅供参考。第一种是设置了使用镜像源加速，dc检查是通过官方源进行的。通过镜像源加速的可能会受到镜像缓存的影响。第二种比较独特。他的设备不管怎么拉取就是拉取不到最新的镜像。但过几天又能拉到了。可以自己排查下。

**Comment by onlyLTY** [comment]
ugreen 2.0.5 zspace 2.0.4应该已经修复
