### ISSUE TITLE
好像有两个镜像点了更新没有用，仍然显示存在新版本

### ISSUE THREAD

**Issue by lovejc0821** [onlyLTY/oneKeyUpdate#46]
![image](https://github.com/onlyLTY/dockerCopilot/assets/29045258/6d5b9b90-d378-44af-8d8f-67ed530535e8)
![image](https://github.com/onlyLTY/dockerCopilot/assets/29045258/69a79b7e-e526-494b-854e-a4787e9a99e9)

**Comment by onlyLTY** [comment]
ugreen 2.0.5 zspace 2.0.4应该已经修复
