### ISSUE TITLE
docker镜像封了。现在拉不下镜像了。

### ISSUE THREAD

**Issue by yang1560** [onlyLTY/oneKeyUpdate#49]
docker镜像封了。现在拉不下镜像了。

**Comment by onlyLTY** [comment]
可以在目标镜像那里替换镜像站，比如要使用dockerproxy.com镜像站拉取ubuntu镜像可以在目标镜像站那里填dockerproxy.com/ubuntu然后点击更新即可

**Comment by reY2ox** [comment]
> 可以在目标镜像那里替换镜像站，比如要使用dockerproxy.com镜像站拉取ubuntu镜像可以在目标镜像站那里填dockerproxy.com/ubuntu然后点击更新即可

能给加个代理接口吗？

**Comment by onlyLTY** [comment]
> > 可以在目标镜像那里替换镜像站，比如要使用dockerproxy.com镜像站拉取ubuntu镜像可以在目标镜像站那里填dockerproxy.com/ubuntu然后点击更新即可
> 
> 能给加个代理接口吗？

dc可以设置代理。使用环境HTTP_PROXY或者HTTPS_PROXY均可。但这个http代理仅能作用在检查容器更新的时候。dc无法修改docker引擎的配置文件，如果需要在拉取镜像时使用代理，请修改docker引擎配置文件

**Comment by qnloft** [comment]
hubURL=https://docker.nju.edu.cn  那这个配置的作用是什么呀？

**Comment by onlyLTY** [comment]
古早版本残留的。目前处于无效状态


onlyLTY








---- qnloft ***@***.***> 在 Thu, 20 Jun 2024 11:29:56 +0800 写到：---





hubURL=https://docker.nju.edu.cn 那这个配置的作用是什么呀？
