### ISSUE TITLE
更新镜像，提示已成功，但是实际好像没更新，仍旧还是显示有新版本。

### ISSUE THREAD

**Issue by liuwaha** [onlyLTY/oneKeyUpdate#50]
前一阵子用得好好的，不知道为什么今天一直没更新成功
![image](https://github.com/onlyLTY/dockerCopilot/assets/150313983/5b96477b-14d5-4cbd-a0f4-d70323ac7577)

**Comment by yydlh** [comment]
dockerhub被墙了

**Comment by onlyLTY** [comment]
存在bug，排查中

**Comment by onlyLTY** [comment]
ugreen 2.0.5 zspace 2.0.4应该已经修复
