### ISSUE TITLE
使用NginxProxyManager代理SSL后无法访问

### ISSUE THREAD

**Issue by codesensi** [onlyLTY/oneKeyUpdate#6]
![image](https://github.com/onlyLTY/oneKeyUpdate/assets/66196408/231d76e8-1042-433c-80e7-9c8a12b8c9d3)
如图，使用了NginxProxyManager代理，并添加了SSL，但是无法访问，请问这个咋解决

**Comment by onlyLTY** [comment]
看起来是nginx反代没有转发csrf导致的。需要设置转发csrf

**Comment by codesensi** [comment]
请问该怎么设置呢，能不能搞成环境配置项

**Comment by onlyLTY** [comment]
这个需要在NginxProxyManager里面设置。具体的话我不太熟悉。

**Comment by codesensi** [comment]
好吧，我研究研究

**Comment by onlyLTY** [comment]
> 

目前确定不需要做其他设置的就是ip直接访问或者就是极空间自带的远程访问，使用极空间自带的远程访问需要勾选代理模式
![image](https://github.com/onlyLTY/oneKeyUpdate/assets/46625336/7923eef3-de05-42e8-b587-0d8f30e54cce)

**Comment by codesensi** [comment]
以前也用过一款这个框架的应用，也有这样的问题，后来作者更新了版本，改成了环境配置项，我也问过了那个作者，他说这个是需要开发者自己做的，奈何我不会这个py

**Comment by onlyLTY** [comment]
> 以前也用过一款这个框架的应用，也有这样的问题，后来作者更新了版本，改成了环境配置项，我也问过了那个作者，他说这个是需要开发者自己做的，奈何我不会这个py

环境配置的话个人猜测就是通过环境配置来开启或者关闭csrf，但由于docker api为危险性，不会提供关闭csrf的环境配置

**Comment by codesensi** [comment]
不是开启或关闭，应该是直接用https的链接替换了程序自己的http代理，有一个环境：变量配置https://ip:port/xxx这种的

**Comment by onlyLTY** [comment]
> 不是开启或关闭，应该是直接用https的链接替换了程序自己的http代理，有一个环境：变量配置[https://ip:port/xxx这种的](https://ip:port/xxx%E8%BF%99%E7%A7%8D%E7%9A%84)

请问有参考项目吗？我去研究下

**Comment by codesensi** [comment]
> > 不是开启或关闭，应该是直接用https的链接替换了程序自己的http代理，有一个环境：变量配置[https://ip:port/xxx这种的](https://ip:port/xxx%E8%BF%99%E7%A7%8D%E7%9A%84)
> 
> 请问有参考项目吗？我去研究下

看我仓库的ptools这个项目，就是这个

**Comment by codesensi** [comment]
> > 不是开启或关闭，应该是直接用https的链接替换了程序自己的http代理，有一个环境：变量配置[https://ip:port/xxx这种的](https://ip:port/xxx%E8%BF%99%E7%A7%8D%E7%9A%84)
> 
> 请问有参考项目吗？我去研究下

https://github.com/eriflleh/ptools/commit/f6703b325bf47dc0b3365fdef30906060a6dc171

**Comment by sssnto** [comment]
找个一个临时的解决办法，可以解决。
编辑  /app/oneKeyUpdate/setting.py 文件(镜像里没有vi和vim，可以考虑将/app/oneKeyUpdate挂载出来，然后本地编辑)，
 在最后一行添加 
CSRF_TRUSTED_ORIGINS = ['https://oku.codesensi.cn:1443']

**Comment by codesensi** [comment]
> 找个一个临时的解决办法，可以解决。 编辑 /app/oneKeyUpdate/setting.py 文件(镜像里没有vi和vim，可以考虑将/app/oneKeyUpdate挂载出来，然后本地编辑)， 在最后一行添加 CSRF_TRUSTED_ORIGINS = ['https://oku.codesensi.cn:1443']

搜嘎，明白了，期待你版本更新之後更簡單解決，啾咪
