### ISSUE TITLE
威联通能用吗？报错HTTPConnectionPool(host='127.0.0.1', port=9123): Max retries exceeded with url: /api/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f3362bfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by xiaosagemisery** [onlyLTY/oneKeyUpdate#7]
具体报错：
HTTPConnectionPool(host='127.0.0.1', port=9123): Max retries exceeded with url: /api/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f3362bfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
在威联通的Container Station中安装的，account就设置为了威联通网页端管理界面的用户名

**Comment by onlyLTY** [comment]
非常抱歉。目前仅适配了极空间设备。如果是其他品牌，建议使用portainer

**Comment by xiaosagemisery** [comment]
@onlyLTY 谢谢

**Comment by onlyLTY** [comment]
现在版本支持了，可以拉取ugreen镜像
