### ISSUE TITLE
oneKeyUpdate的更新，只能新建镜像吗？

### ISSUE THREAD

**Issue by Mydong** [onlyLTY/oneKeyUpdate#8]
感谢作者出了这么好的东西；
现在更新oneKeyUpdate的时候，是不是只能暂停容器，然后手动更新oneKeyUpdate的镜像。

**Comment by onlyLTY** [comment]
只有大更新需要这样，其他小更新重启容器即可自动拉取最新代码

**Comment by Mydong** [comment]
好的好的  我试试 重启下容器  感谢
